services:
  - type: web
    name: flask-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_model.py"  # ใช้คำสั่งนี้เพื่อรัน Flask API
    region: "us"